corerouter: use patched version of bird2 and add proper inbound metrics
freifunk-berlin/bbb-configs pull request #1087
Opened 2024-11-22 16:53 UTC by spolack

please test

2024-11-22 17:45 UTC, Noki requested changes
works for me even without the requested changes.

2024-11-22 17:45 UTC, Noki commented on roles/cfg_openwrt/templates/corerouter/bird.conf.j2
>    {% set default_mesh_metric = hostvars[inventory_hostname].get('mesh_metric_adhoc_' ~ nw.get('mesh_radio'), mesh_metric_default_in) %}
the comment should be moved up and the line with `set default_mesh_metric` should be removed as it does not do anything here anymore

2024-11-22 20:46 UTC, PolynomialDivision approved these changes

2024-11-22 20:50 UTC, PolynomialDivision commented
oh wait, please add something to commit message

2024-11-22 20:51 UTC, PolynomialDivision commented
Please add

```
Link: https://bird.network.cz/pipermail/bird-users/2023-February/016705.html
```

2024-11-23 06:58 UTC, Noki approved these changes

2024-11-23 07:52 UTC, merged