model: add fritzbox 4040 dsa model for snapshot
freifunk-berlin/bbb-configs pull request #375
Opened 2022-11-10 18:26 UTC by PolynomialDivision

2022-11-10 18:39 UTC, Noki requested changes

2022-11-10 18:39 UTC, Noki commented on group_vars/model_avm_fritzbox_4040_dsa.yml
> +    hwmode: 11a
hwmode is deprecated. please use band instead. please also set htmode_prefix.

2022-11-10 18:39 UTC, Noki commented on group_vars/model_avm_fritzbox_4040_dsa.yml
> +    hwmode: 11g
same as above

2022-11-12 13:52 UTC, spolack commented
```
Error: _vars/model_avm_fritzbox_4040_dsa.yml:1:1: [error] missing document start "---" (document-start)
```

Please fix that lint error, then feel free to merge

2022-11-12 18:17 UTC, Noki commented
htmode_prefix is still missing

2022-11-12 18:26 UTC, spolack commented
You are right, sorry!

2022-11-29 11:28 UTC, Noki approved these changes

2022-11-29 11:37 UTC, merged