location_philmel: convert to new location file and add new accesspoints
freifunk-berlin/bbb-configs pull request #609
Opened 2023-11-29 22:08 UTC by Petrella

Philmel needed some adjustements due to adding some access points with special config and ssid names

2023-11-30 04:59 UTC, Noki requested changes
When switching to the single-file-format, the definitions needs to be moved. Please delete the files in group_vars and host_vars so they only exist in locations/philmel.yml from now on.

2023-11-30 04:59 UTC, Noki commented on group_vars/all/wireless_profiles.yml
This file should not be changed. Wireless_profiles moved to the locations and should not be added back here.

2023-12-13 16:17 UTC, FFHener commented
Please mark the pr as a draft until its ready for a review

2023-12-15 14:07 UTC, FFHener commented
Closing as there is a new version of this PR

2023-12-15 14:07 UTC, closed without merging