Treewide: Add nicer names to modelfiles
freifunk-berlin/bbb-configs pull request #750
Opened 2024-01-29 17:34 UTC by FFHener

This is related to #749

2024-01-29 18:46 UTC, Noki requested changes

2024-01-29 18:46 UTC, Noki commented on group_vars/model_ubnt_edgerouter_x_sfp.yml
> +model_nice: EdgeRouter x-SFP
should be EdgeRouter X SFP

2024-01-29 18:46 UTC, Noki commented on group_vars/model_ubnt_nanostation_ac_loco.yml
> +model_nice: Nanostation AC loco
should be "Loco"

2024-01-29 18:46 UTC, Noki commented on group_vars/model_x86_64.yml
> +model_nice: Virtual Machine
this can also be bare metal

2024-01-30 12:20 UTC, FFHener commented on group_vars/model_x86_64.yml
> +model_nice: Virtual Machine
What do you think about the new name?

2024-01-30 13:06 UTC, Noki approved these changes

2024-01-30 15:49 UTC, merged