teufelsberg-security: add location
freifunk-berlin/bbb-configs pull request #762
Opened 2024-02-05 14:03 UTC by noxilixon

Mac overwrite for mesh ap needs to be added. I don't have access to a device right now.

2024-02-05 15:19 UTC, FFHener requested changes

2024-02-05 15:19 UTC, FFHener commented on locations/teufelssecurity.yml
> +    prefix: 10.31.243.64/32
This Prefix needs to be part of the Meshsubnet

2024-02-05 16:36 UTC, FFHener approved these changes
lgtm

2024-02-05 16:37 UTC, FFHener commented
Will keep this as a draft until we builded this locations as there might be changes again

2024-07-17 01:26 UTC, noxilixon commented
I updated the coordinates. Were there other changes during the installation @FFHener ? If not we can merge this.

2024-07-18 14:20 UTC, noxilixon commented on locations/teufelsberg.yml
> +  teufelsberg-ap1: 44-20
Removed it, not sure why it existed in the first place.

2024-07-18 15:10 UTC, Noki commented on locations/teufelsberg.yml
> +longitude: 13.23970
Don't change this. It's the core location at the tower.

2024-07-19 00:22 UTC, merged