treewide: add option for specifing a wifiprefix
freifunk-berlin/bbb-configs pull request #85
Opened 2021-11-01 13:14 UTC by PolynomialDivision

You can now do "whatever.freifunk.net" by setting in your locaiton
in the wireless_profiles.yml.

Updated locations:
- colbe15
- wilgu10

2021-11-01 20:19 UTC, Akira25 requested changes
I'm against the idea of this PR. Berlin community agreed on having `berlin.freifunk.net` as SSID quite a time ago and has done it ever since.

Having seperate SSIDs per location is really bad. It prevents clients from roaming. In addition users will need to actively look for freifunk-wifis in their reach, instead of just connecting to them.

This PR would introduce a big mess in ther Berlin Freifunk Network.

2021-11-01 20:49 UTC, Akira25 commented
We had a long discussion on this in our matrix channel. we agreed on this:

On every location, that broadcasts a location-spezific SSID, there must be an additional wifi, that broadcasts on the standard SSID. @PolynomialDivision please change the PR to ensure that, I will approve then. :)

2022-01-24 18:48 UTC, spolack commented
@nick are you planning to implement the requested changes? Otherwise i'd like to close that PR

2022-01-24 19:25 UTC, PolynomialDivision commented
Lets close.

2022-01-24 19:25 UTC, closed without merging